// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE_chnD3vXZ1vS_IOJIncMOsR4egwbHHQ',
    appId: '1:1094295822946:web:7dc3b71d2fc76d845be73b',
    messagingSenderId: '1094295822946',
    projectId: 'wfyp-62cff',
    authDomain: 'wfyp-62cff.firebaseapp.com',
    storageBucket: 'wfyp-62cff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8VcAGPkKbA6cdcIf2DSrosr2OqDj1aBw',
    appId: '1:1094295822946:android:195357b1adc51e9f5be73b',
    messagingSenderId: '1094295822946',
    projectId: 'wfyp-62cff',
    storageBucket: 'wfyp-62cff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4QkkcxJa50jjgWZYiqYsHAx0aWM9yxYo',
    appId: '1:1094295822946:ios:d3febcea4ab863a05be73b',
    messagingSenderId: '1094295822946',
    projectId: 'wfyp-62cff',
    storageBucket: 'wfyp-62cff.appspot.com',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4QkkcxJa50jjgWZYiqYsHAx0aWM9yxYo',
    appId: '1:1094295822946:ios:d3febcea4ab863a05be73b',
    messagingSenderId: '1094295822946',
    projectId: 'wfyp-62cff',
    storageBucket: 'wfyp-62cff.appspot.com',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE_chnD3vXZ1vS_IOJIncMOsR4egwbHHQ',
    appId: '1:1094295822946:web:8cc9c95fb76a99115be73b',
    messagingSenderId: '1094295822946',
    projectId: 'wfyp-62cff',
    authDomain: 'wfyp-62cff.firebaseapp.com',
    storageBucket: 'wfyp-62cff.appspot.com',
  );
}
